sandbox_mode = "workspace-write"
approval_policy = "on-failure"
model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"

[features]
web_search_request = true
rmcp_client = true

[sandbox_workspace_write]
network_access = true
